FROM registry.access.redhat.com/ubi8/openjdk-11-runtime:1.17-5

LABEL org.opencontainers.image.authors="Fugerit" \
      org.opencontainers.image.revision="1.17-5-fontconfig"

USER root

RUN microdnf install fontconfig

ENV OSFONTDIR=/usr/share/fonts
RUN chmod -R o+w /usr/share/fonts\
  && fc-cache --really-force --verbose